services:
  nginx:
    container_name: web
    image: nginx:alpine
    ports:
      - 3000:80
    volumes:
      - ./dist:/usr/share/nginx/html

  surrealdb:
    container_name: db
    image: surrealdb/surrealdb:v2
    ports:
      - 8000:8000
    command:
      - start
      - memory
      - -A
      - --no-banner
      # - --log=trace
      # - --log=info
      # - --unauthenticated
      - --user=root
      - --pass=root
      - --bind=0.0.0.0:8000
